### ISSUE TITLE
Upload a complete project

### ISSUE THREAD

**Issue by dintadelin** [bodnaristvan/pebble-diet-reminder#1]
Hi! I'm interested in your amazing project. I would like to modify it. When I build your project in Pebble SDK, it can't be built. I'm wondering if you upload the full project. I hope you don't mind. Thank you~

![screenshot from 2015-05-08 17 20 19](https://cloud.githubusercontent.com/assets/11527085/7513398/11f1562e-f4de-11e4-9ebf-1bea58117b83.png)

**Comment by bodnaristvan** [comment]
Hey @dintadelin, I was using CloudPebble, and pushed files to github through the interface, so AFAIK everything should be there. Haven't used the local sdk yet, because i just wanted to try out developing for Pebble, so i can't confirm that it's running fine for me locally..
Have you tried importing the project to CloudPebble, and compile it there?

**Comment by bodnaristvan** [comment]
This is what i get in CloudPebble:

![screenshot 2015-05-07 14 34 42](https://cloud.githubusercontent.com/assets/710358/7515315/43a024ba-f4c6-11e4-9031-64d7aa07f2e9.png)

**Comment by dintadelin** [comment]
Hi, thank you very much for the response. Because your project is a pebble.js project, so I tried to run your project on my cloudpebble. But I don't know why, my cloudpebble doesn't want to load. It keeps said "emulator boot failed : out of capacity". I don't know why, is there any problem with my cloudpebble? Because I already tried it in some computers.

**Comment by dintadelin** [comment]
![screenshot from 2015-05-08 23 29 47](https://cloud.githubusercontent.com/assets/11527085/7520558/b30a6482-f511-11e4-86b0-54866fb095e9.png)

**Comment by dintadelin** [comment]
Hi Bodnár István! This morning I tried your project in Mozilla Firefox and it worked! I was running your project in Chrome. Still don't know why it only works in Mozilla Firefox. Thank you very much Bodnár István! Hope you wouldn't mind helping me again hehe.
